### ISSUE TITLE
Issue with the rpm-ostree

### ISSUE THREAD

**Issue by samberthol** [jhrozek/sssd-openshift#1]
Trying this on a RH CodeReady Containers (latest) for a customer who is actually interested with this POC.
The 'rpm-ostree override' fails for all the packages provided with this error : 
nothing provides libldb.so.1()(64bit) needed by sssd-ad-2.0.0-43.el8.3.3.x86_64

I guess the dependencies are broken by a later version of CoreOS. I have libldb.so.2.0.7.

**Comment by jhrozek** [comment]
tl;dr this repo is no longer maintained as we couldn't convince others in OCP that logging to the nodes is something you should do, ever. We might revisit it at some later point because the issues that prompted us to start this POC are still valid (e.g. no good auditing of who did what when you just oc debug to a node).

I'll shoot you a mail to your work address and connect you with people who might carry a similar work forward. But in the short term, this won't make its way to OCP.

**Comment by samberthol** [comment]
Thank you very much for following up on this although the project is archived. Responding by mail.
